### PR TITLE
Ticking API

### PR DESCRIPTION
**Pull request by FxMorin**
Use the `PistonTicking` interface on classes extending `Block` or `BlockEntity`, it will allow them to tick while being pushed by a piston through the provided method.

---

**New Config options:**
`tickingApi` - Toggle the ticking API, this will prevent all ticking-based features from working!
`cookWhileMoving` - Continues ticking furnace type blocks as they are moving

---

`cookWhileMoving` is the `tickingApi` example feature. Basically showing you that you can make furnaces cook while moving without any problems.

---

**Things to consider in the future:**
- Having a wrapped `BlockGetter` that automatically prevents world changes while moving could be pretty beneficial. #30 currently has one that we could use later on for this
- Should also allow `animtateTick` to run while being moved

### CODE REVIEW

**Review by SpaceWalkerRS — COMMENTED** [review]
I'm not sure I'm convinced this is the way to go about it. I feel like it'll lead to either a lot of code duplication, where the `onMovingTick` implementation does almost exactly the same as the `tick` implementation, or a lot of cases where `onMovingTick` just calls `tick` and any behavioral changes are done through Mixin. So why not just call the normal `tick` method directly? The block entity could keep track of its status (stationary/moving/merging/whatever else is relevant) and use that for behavioral differences in the `tick` implementation. Perhaps it makes sense to force block entities to 'opt into' moving while ticking through a `canTickWhileMoving` method or something to make sure it doesn't accidentally break.

**Comment by FxMorin** [comment]
@SpaceWalkerRS Ok so you are fine with the `Block` having `onMovingTick()` but you want the `BlockEntity` to use `tick()` however `BlockEntity` does not have a `tick()` method.
`serverTick()` is static and cannot be targeted easily, plus different block entities have different methods. Most also don't have one

For example:
`HopperBlockEntity` - `public static void pushItemsTick(Level, BlockPos, BlockState, HopperBlockEntity)`
`SculkCatalystBlockEntity` - `public static void serverTick(Level, BlockPos, BlockState, SculkCatalystBlockEntity)`
`CampfireBlockEntity`:
- isClient & LIT: `public static void particleTick(Level, BlockPos, BlockState, CampfireBlockEntity)`
- not isClient & LIT: `public static void cookTick(Level, BlockPos, BlockState, CampfireBlockEntity)`
- not isClient & not LIT: `public static void cooldownTick(Level, BlockPos, BlockState, CampfireBlockEntity)`

Another thing to take into account is that some mods may want to add ticking functionality when moving but not when still. So making there block entity ticking for no reason is not great.
We don't need the block entity to be ticking since we are passing the tick from the moving block being ticked, meaning we have full control over how we tick these block entities.

That's why I'm using my own method here

**Comment by SpaceWalkerRS** [comment]
Right, I forgot about the stupid ticker system block entities have now. It could still work if you just fetched the moved block entities ticker and invoked that I guess, but I can't blame you for avoiding the ticker system at all costs.

**Comment by FxMorin** [comment]
Ya I would rather it be an opt-in more customizable option

**Comment by SpaceWalkerRS** [comment]
I'm still not a fan of the `FakeBlockPos` thing, it just feels so jank xD
Then again the alternatives are to completely duplicate that `serverTick` method or keep a boolean in the block entity and toggle it when the moving tick is called, neither of which are ideal.

**Review by SpaceWalkerRS — APPROVED** [review]

**Pull request merged**
